name: Primer action

on:
  push:
    branches:
      - main

jobs:
  primer_action:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hello, world!"
      - name: dime la fecha
        run: echo "La fecha es $(date)"
      - run: ls -la